### PR TITLE
Selecting/deleting from sideBar with keys

### PR DESCRIPTION
**Pull request by Breakster**
Hey Arranger,

I want to start making some small changes to iSoul, to work out some quirks, and make it more usable overal. Are you still going to work on this? Will you still be merging changes? It would be nice to hear about the status of iSoul.

I am new to open source projects, so this is also a learning experience for me.

Fixes:
- Fixed responder chain for ExpandingSideBar and MainViewController
- Fixed removing items from the sidebar with delete/forward delete keys
- Added support to navigate through sidebar w/ arrow keys

### CODE REVIEW

**Comment by djbe** [comment]
Thanks for the changes, but before I merge it, could you change the following: In _ExpandingSidebar.m_ you use the actual keycodes when comparing them to the received value. That's not the best way to do things, either store those values (125, 126, ...) in constants or (if available) use predefined definitions.

The rest seems ok (nice optimisation in the hashing function, maybe add a comment explaining it, took a couple of seconds before I got it).

**Comment by arranger1044** [comment]
Thanks Breakster,
    the current status of iSoul is: 'under_development'. Since the last nightly build release not much has been done, I do still have real life issues that I must take care of (and I image David has his own ones too). 
That said, you cannot said the project is 'dead', it is just 'stalling' waiting for new contributors like you that can produce a few fixes with good will. 
Please follow David's suggestion in adjusting some line of code, and he will then merge everything (thanks David).
David, if the changes are relevant, can we push an update through Sparkle?

Il giorno 14/ott/2012, alle ore 00:33, Breakster ha scritto:

**Comment by Breakster** [comment]
Ok, I changed a few things as you suggested and pushed the changes. Should I make a second pull request, or is this ok?

Even though I don't use iSoul that much myself, I like the project and I would love to add more improvements in the future. Should I notify you for every few small changes? What is the common way of work?

**Comment by djbe** [comment]
Jup, very nice.

Well, make a few of these pull requests and if everything's okay @arranger1044 can then give you direct repo access (so that you can directly pull your changes upstream without making requests).

@arranger1044 maybe, I was having some issues with the certificate the last time I tried.

**Comment by arranger1044** [comment]
@Breakster as David said, if you are willingly to commit so other fixes you can get free access to the repo in the future. We are glad to see new forces joing us
@djbe which issues are you experiencing with sparkle?

**Pull request merged**
